from __future__ import annotations

from pathlib import Path

import joblib
from fastapi import FastAPI, HTTPException, Query
from pydantic import BaseModel

from forecasting_service.config import settings


class ForecastPoint(BaseModel):
    date: str
    prediction: float


class ForecastResponse(BaseModel):
    state: str
    best_model: str
    horizon: int
    forecast: list[ForecastPoint]


app = FastAPI(
    title="State Sales Forecasting API",
    version="0.1.0",
    description="Serves next-week sales forecasts generated by the model selection pipeline.",
)


def load_registry(path: Path | None = None) -> dict:
    artifact = path or settings.artifact_path
    if not artifact.exists():
        raise FileNotFoundError(
            f"Forecast artifact not found at {artifact}. Run `python -m forecasting_service.training` first."
        )
    return joblib.load(artifact)


@app.on_event("startup")
def startup() -> None:
    app.state.registry = load_registry()


@app.get("/health")
def health() -> dict:
    return {
        "status": "ok",
        "artifact_created_at": app.state.registry.get("created_at"),
        "states_loaded": len(app.state.registry.get("states", {})),
    }


@app.get("/states")
def states() -> dict:
    return {"states": sorted(app.state.registry.get("states", {}).keys())}


@app.get("/models")
def models() -> dict:
    return {
        state: {
            "best_model": payload["best_model"],
            "metrics": payload["metrics"],
            "errors": payload.get("errors", {}),
        }
        for state, payload in app.state.registry.get("states", {}).items()
    }


@app.get("/forecast/{state}", response_model=ForecastResponse)
def forecast(
    state: str,
    horizon: int = Query(default=8, ge=1, le=8, description="Number of future weekly predictions to return."),
) -> ForecastResponse:
    payload = app.state.registry.get("states", {}).get(state)
    if payload is None:
        raise HTTPException(status_code=404, detail=f"Unknown state: {state}")
    return ForecastResponse(
        state=state,
        best_model=payload["best_model"],
        horizon=horizon,
        forecast=payload["forecast"][:horizon],
    )
